# Generated by Django 5.2.7 on 2025-11-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20),
        ),
    ]
