# Generated by Django 5.2.7 on 2025-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos/'),
        ),
    ]
